---
- name: Install Jenkins on Ubuntu 24
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
          - ca-certificates
        state: present

    - name: Add Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository
      shell: |
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/ | tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Allow Jenkins port 8080
      ufw:
        rule: allow
        port: '8080'
        proto: tcp
