---

- hosts: all
  become: true
  pre_tasks:

  - name: create tom user
    tags: always
    user:
      name: tom
      groups: root

  - name: add ssh key for tom
    tags: always
    authorized_key:
      user: tom
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBYwhRUl85GepwLzYOV9tPgTDjgFtz/AsJ59kiDtRS4X ansible"

  - name: add sudoers file for tom
    tags: always
    copy:
      src: sudoer_tom
      dest: /etc/sudoers.d/tom
      owner: root
      group: root
      mode: 0440

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


